START TRANSACTION;

UPDATE test_table SET value = 200 WHERE id = 1;

SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

START TRANSACTION;
SELECT value FROM test_table WHERE id = 1;
COMMIT;

ROLLBACK;
